### ISSUE TITLE
Parentheses after string title causes an ICE

### ISSUE THREAD

**Issue by reddraggone9** [reem/stainless#49]
### Steps to reproduce:

1. Create a new project
   ```sh
   $ cargo new stainless-fail
   $ cd stainless-fail
   $ echo 'stainless = { git = "https://github.com/reem/stainless.git" }' >> Cargo.toml
   ```

2. Replace `src/lib.rs` with the following:
   ```rust
   #![feature(plugin,const_fn)]
   #![plugin(stainless)]

   describe! a_panic {
       it "fails to parse"() {
           assert!(true);
       }
   }
   ```

3. Boom
   ```sh
   $ cargo test
   ```
   Which, among other things, get us `error: internal compiler error: unexpected panic`.

### Versions
```sh
$ rustc --version
rustc 1.9.0-nightly (388ccda45 2016-03-07)
$ cat Cargo.lock 
[root]
name = "stainless-fail"
version = "0.1.0"
dependencies = [
 "stainless 0.1.4 (git+https://github.com/reem/stainless.git)",
]

[[package]]
name = "stainless"
version = "0.1.4"
source = "git+https://github.com/reem/stainless.git#f11ab9f707bec862739538a8e420de9b38cd41d1"
```

It would be nice if this gave a better error. It took me a while to figure out that I had screwed up when converting existing tests.

**Comment by reem** [comment]
Can you paste the full error output as well?

**Comment by reddraggone9** [comment]
With backtrace for your reading pleasure:

```
$ RUST_BACKTRACE=1 cargo test
   Compiling stainless-fail v0.1.0 (file:///home/lee/stainless-fail)
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/libsyntax/errors/mod.rs:360
stack backtrace:
   1:     0x7fd964cba130 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x7fd964cc348b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44997
   3:     0x7fd964cc2fe3 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x7fd964c865cc - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x7fd960a7f89f - sys_common::unwind::begin_unwind::h17493743739403980774
   6:     0x7fd960a86f4f - errors::DiagnosticBuilder<'a>.Drop::drop::h4cc60d9859c311b1uCd
   7:     0x7fd958d83c4c - syntax..errors..DiagnosticBuilder::drop.14021::h3328dcec978171c1
   8:     0x7fd958d86556 - core..result..Result<syntax..ptr..P<syntax..ast..Block>, syntax..errors..DiagnosticBuilder>::drop.14255::hb35913e11e9fd696
   9:     0x7fd958d864e8 - result::Result<T, E>::ok::h7997844364068907197
                        at ../src/libcore/result.rs:326
  10:     0x7fd958d83897 - parse::Test.Parse<TestConfig>::parse::hcdbd53a071052996eea
                        at /home/lee/.multirust/cargo/git/checkouts/stainless-1201eb9e05f085b5/master/src/parse.rs:28
  11:     0x7fd958d8174a - parse::DescribeState.Parse<(codemap..Span, &'a mut base..ExtCtxt<'b>, Option<ast..Ident>)>::parse::hba2c8d541af6e962gia
                        at /home/lee/.multirust/cargo/git/checkouts/stainless-1201eb9e05f085b5/master/src/parse.rs:135
  12:     0x7fd958d532f1 - describe::describe::h2747228fd4907c2eSca
                        at /home/lee/.multirust/cargo/git/checkouts/stainless-1201eb9e05f085b5/master/src/describe.rs:62
  13:     0x7fd958d535dd - fn(&mut syntax..ext..base..ExtCtxt, syntax..codemap..Span, syntax..ast..Ident, collections..vec..Vec<syntax..ast..TokenTree>) .> Box<syntax..ext..base..MacResult> $u7b$describe..describe$u7d$::fn_pointer_shim.12640::h9c2d6bd26469c047
  14:     0x7fd958d53526 - ext::base::F.IdentMacroExpander::expand::h3655288564491858562
                        at ../src/libsyntax/ext/base.rs:199
  15:     0x7fd960d35f7f - ext::expand::expand_item_mac::h348a1dabf0095ec5mO9
  16:     0x7fd960d248c1 - ext::expand::expand_annotatable::h73107255e9f0f12bnia
  17:     0x7fd960d21a88 - ext::expand::expand_item::hc83af09c50bbf118AL9
  18:     0x7fd960d2fb3e - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::hab0af15358905887ZAa
  19:     0x7fd960d2f773 - fold::noop_fold_mod::h1340742748614032109
  20:     0x7fd960d290e2 - ext::expand::expand_item_kind::hb1b28fc55010d656bM9
  21:     0x7fd960d6543e - fold::noop_fold_item_simple::h7249558123432585226
  22:     0x7fd960d64fb0 - fold::noop_fold_item::h16800801704387591837
  23:     0x7fd960d26052 - ext::expand::expand_annotatable::h73107255e9f0f12bnia
  24:     0x7fd960d21a88 - ext::expand::expand_item::hc83af09c50bbf118AL9
  25:     0x7fd960d2fd4c - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::hab0af15358905887ZAa
  26:     0x7fd960d71289 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_crate::hc3a7ff803a651d771za
  27:     0x7fd960d7276a - ext::expand::expand_crate::h50433f6c34fb916aPJa
  28:     0x7fd96522c1d1 - driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::closure.35539
  29:     0x7fd9651d9907 - driver::phase_2_configure_and_expand::h125085c20f4f12318Aa
  30:     0x7fd9651bd101 - driver::compile_input::h374defb7e6bbab0fKca
  31:     0x7fd9651acbdf - run_compiler::he060f7dfa5229ad78Oc
  32:     0x7fd9651aa301 - sys_common::unwind::try::try_fn::h17712212266958575598
  33:     0x7fd964cb7b1b - __rust_try
  34:     0x7fd964cafdcd - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  35:     0x7fd9651aab4a - boxed::F.FnBox<A>::call_box::h14363784912673834417
  36:     0x7fd964cc1a59 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  37:     0x7fd95d434423 - start_thread
  38:     0x7fd964935cbc - clone
  39:                0x0 - <unknown>

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
thread 'rustc' panicked at 'explicit panic', ../src/libsyntax/errors/mod.rs:360
stack backtrace:
   1:     0x7f5ad194d130 - sys::backtrace::tracing::imp::write::h578d6e47592a4041cHv
   2:     0x7f5ad195648b - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44997
   3:     0x7f5ad1955fe3 - panicking::default_handler::hffa00c845e94c6581nA
   4:     0x7f5ad19195cc - sys_common::unwind::begin_unwind_inner::hd824946792143cc8vvu
   5:     0x7f5acd71289f - sys_common::unwind::begin_unwind::h17493743739403980774
   6:     0x7f5acd719f4f - errors::DiagnosticBuilder<'a>.Drop::drop::h4cc60d9859c311b1uCd
   7:     0x7f5ac5983c4c - syntax..errors..DiagnosticBuilder::drop.14021::h3328dcec978171c1
   8:     0x7f5ac5986556 - core..result..Result<syntax..ptr..P<syntax..ast..Block>, syntax..errors..DiagnosticBuilder>::drop.14255::hb35913e11e9fd696
   9:     0x7f5ac59864e8 - result::Result<T, E>::ok::h7997844364068907197
                        at ../src/libcore/result.rs:326
  10:     0x7f5ac5983897 - parse::Test.Parse<TestConfig>::parse::hcdbd53a071052996eea
                        at /home/lee/.multirust/cargo/git/checkouts/stainless-1201eb9e05f085b5/master/src/parse.rs:28
  11:     0x7f5ac598174a - parse::DescribeState.Parse<(codemap..Span, &'a mut base..ExtCtxt<'b>, Option<ast..Ident>)>::parse::hba2c8d541af6e962gia
                        at /home/lee/.multirust/cargo/git/checkouts/stainless-1201eb9e05f085b5/master/src/parse.rs:135
  12:     0x7f5ac59532f1 - describe::describe::h2747228fd4907c2eSca
                        at /home/lee/.multirust/cargo/git/checkouts/stainless-1201eb9e05f085b5/master/src/describe.rs:62
  13:     0x7f5ac59535dd - fn(&mut syntax..ext..base..ExtCtxt, syntax..codemap..Span, syntax..ast..Ident, collections..vec..Vec<syntax..ast..TokenTree>) .> Box<syntax..ext..base..MacResult> $u7b$describe..describe$u7d$::fn_pointer_shim.12640::h9c2d6bd26469c047
  14:     0x7f5ac5953526 - ext::base::F.IdentMacroExpander::expand::h3655288564491858562
                        at ../src/libsyntax/ext/base.rs:199
  15:     0x7f5acd9c8f7f - ext::expand::expand_item_mac::h348a1dabf0095ec5mO9
  16:     0x7f5acd9b78c1 - ext::expand::expand_annotatable::h73107255e9f0f12bnia
  17:     0x7f5acd9b4a88 - ext::expand::expand_item::hc83af09c50bbf118AL9
  18:     0x7f5acd9c2b3e - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::hab0af15358905887ZAa
  19:     0x7f5acd9c2773 - fold::noop_fold_mod::h1340742748614032109
  20:     0x7f5acd9bc0e2 - ext::expand::expand_item_kind::hb1b28fc55010d656bM9
  21:     0x7f5acd9f843e - fold::noop_fold_item_simple::h7249558123432585226
  22:     0x7f5acd9f7fb0 - fold::noop_fold_item::h16800801704387591837
  23:     0x7f5acd9b9052 - ext::expand::expand_annotatable::h73107255e9f0f12bnia
  24:     0x7f5acd9b4a88 - ext::expand::expand_item::hc83af09c50bbf118AL9
  25:     0x7f5acd9c2d4c - ext::expand::MacroExpander<'a, 'b>.Folder::fold_item::hab0af15358905887ZAa
  26:     0x7f5acda04289 - ext::expand::MacroExpander<'a, 'b>.Folder::fold_crate::hc3a7ff803a651d771za
  27:     0x7f5acda0576a - ext::expand::expand_crate::h50433f6c34fb916aPJa
  28:     0x7f5ad1ebf1d1 - driver::phase_2_configure_and_expand::_$u7b$$u7b$closure$u7d$$u7d$::closure.35539
  29:     0x7f5ad1e6c907 - driver::phase_2_configure_and_expand::h125085c20f4f12318Aa
  30:     0x7f5ad1e50101 - driver::compile_input::h374defb7e6bbab0fKca
  31:     0x7f5ad1e3fbdf - run_compiler::he060f7dfa5229ad78Oc
  32:     0x7f5ad1e3d301 - sys_common::unwind::try::try_fn::h17712212266958575598
  33:     0x7f5ad194ab1b - __rust_try
  34:     0x7f5ad1942dcd - sys_common::unwind::inner_try::h8ac2089dadb4381bxsu
  35:     0x7f5ad1e3db4a - boxed::F.FnBox<A>::call_box::h14363784912673834417
  36:     0x7f5ad1954a59 - sys::thread::Thread::new::thread_start::hd111df90784ef3b2llz
  37:     0x7f5aca0c7423 - start_thread
  38:     0x7f5ad15c8cbc - clone
  39:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
Could not compile `stainless-fail`.

To learn more, run the command again with --verbose.
```

**Comment by reem** [comment]
These errors:

```
error: internal compiler error: Error constructed but not emitted
error: internal compiler error: Error constructed but not emitted
```

seem like they could come from a bug in stainless. Will investigate.

**Comment by echochamber** [comment]
I don't believe the above is a bug. I think thats just what happens when there's a panic! during the compilation itself (in this case, during the macro expansion step).
